<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Device extends BaseController{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Device_model');
    } 

    /*
     * Listing of devices
     */
    function index()
    {
        $data['devices'] = $this->Device_model->get_all_devices();
        
        $data['_view'] = 'device/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new device
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'owner_id' => $this->input->post('owner_id'),
				'device_type' => $this->input->post('device_type'),
				'device_sn' => $this->input->post('device_sn'),
				'device_other' => $this->input->post('device_other'),
				'device_description' => $this->input->post('device_description'),
            );
            
            $device_id = $this->Device_model->add_device($params);
            redirect('device/index');
        }
        else
        {            
            $data['_view'] = 'device/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a device
     */
    function edit($device_id)
    {   
        // check if the device exists before trying to edit it
        $data['device'] = $this->Device_model->get_device($device_id);
        
        if(isset($data['device']['device_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'owner_id' => $this->input->post('owner_id'),
					'device_type' => $this->input->post('device_type'),
					'device_sn' => $this->input->post('device_sn'),
					'device_other' => $this->input->post('device_other'),
					'device_description' => $this->input->post('device_description'),
                );

                $this->Device_model->update_device($device_id,$params);            
                redirect('device/index');
            }
            else
            {
                $data['_view'] = 'device/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The device you are trying to edit does not exist.');
    } 

    /*
     * Deleting device
     */
    function remove($device_id)
    {
        $device = $this->Device_model->get_device($device_id);

        // check if the device exists before trying to delete it
        if(isset($device['device_id']))
        {
            $this->Device_model->delete_device($device_id);
            redirect('device/index');
        }
        else
            show_error('The device you are trying to delete does not exist.');
    }
    
}
