<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Owner extends BaseController{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Owner_model');
    } 

    /*
     * Listing of owners
     */
    function index()
    {
        $data['owners'] = $this->Owner_model->get_all_owners();
        
        $data['_view'] = 'owner/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new owner
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'first_name' => $this->input->post('first_name'),
				'last_name' => $this->input->post('last_name'),
				'street' => $this->input->post('street'),
				'city' => $this->input->post('city'),
				'parish' => $this->input->post('parish'),
				'phone_1' => $this->input->post('phone_1'),
				'phone_2' => $this->input->post('phone_2'),
				'email_address' => $this->input->post('email_address'),
            );
            
            $owner_id = $this->Owner_model->add_owner($params);
            redirect('owner/index');
        }
        else
        {            
            $data['_view'] = 'owner/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a owner
     */
    function edit($owner_id)
    {   
        // check if the owner exists before trying to edit it
        $data['owner'] = $this->Owner_model->get_owner($owner_id);
        
        if(isset($data['owner']['owner_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'first_name' => $this->input->post('first_name'),
					'last_name' => $this->input->post('last_name'),
					'street' => $this->input->post('street'),
					'city' => $this->input->post('city'),
					'parish' => $this->input->post('parish'),
					'phone_1' => $this->input->post('phone_1'),
					'phone_2' => $this->input->post('phone_2'),
					'email_address' => $this->input->post('email_address'),
                );

                $this->Owner_model->update_owner($owner_id,$params);            
                redirect('owner/index');
            }
            else
            {
                $data['_view'] = 'owner/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The owner you are trying to edit does not exist.');
    } 

    /*
     * Deleting owner
     */
    function remove($owner_id)
    {
        $owner = $this->Owner_model->get_owner($owner_id);

        // check if the owner exists before trying to delete it
        if(isset($owner['owner_id']))
        {
            $this->Owner_model->delete_owner($owner_id);
            redirect('owner/index');
        }
        else
            show_error('The owner you are trying to delete does not exist.');
    }
    
}
