<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Alert_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get alert by alert_id
     */
    function get_alert($alert_id)
    {
        return $this->db->get_where('alerts',array('alert_id'=>$alert_id))->row_array();
    }
        
    /*
     * Get all alerts
     */
    function get_all_alerts()
    {
        $this->db->order_by('alert_id', 'desc');
        return $this->db->get('alerts')->result_array();
    }
        
    /*
     * function to add new alert
     */
    function add_alert($params)
    {
        $this->db->insert('alerts',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update alert
     */
    function update_alert($alert_id,$params)
    {
        $this->db->where('alert_id',$alert_id);
        return $this->db->update('alerts',$params);
    }
    
    /*
     * function to delete alert
     */
    function delete_alert($alert_id)
    {
        return $this->db->delete('alerts',array('alert_id'=>$alert_id));
    }
}
