<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Device_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get device by device_id
     */
    function get_device($device_id)
    {
        return $this->db->get_where('devices',array('device_id'=>$device_id))->row_array();
    }
        
    /*
     * Get all devices
     */
    function get_all_devices()
    {
        $this->db->order_by('device_id', 'desc');
        return $this->db->get('devices')->result_array();
    }
        
    /*
     * function to add new device
     */
    function add_device($params)
    {
        $this->db->insert('devices',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update device
     */
    function update_device($device_id,$params)
    {
        $this->db->where('device_id',$device_id);
        return $this->db->update('devices',$params);
    }
    
    /*
     * function to delete device
     */
    function delete_device($device_id)
    {
        return $this->db->delete('devices',array('device_id'=>$device_id));
    }
}
