<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Owner_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get owner by owner_id
     */
    function get_owner($owner_id)
    {
        return $this->db->get_where('owners',array('owner_id'=>$owner_id))->row_array();
    }
        
    /*
     * Get all owners
     */
    function get_all_owners()
    {
        $this->db->order_by('owner_id', 'desc');
        return $this->db->get('owners')->result_array();
    }
        
    /*
     * function to add new owner
     */
    function add_owner($params)
    {
        $this->db->insert('owners',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update owner
     */
    function update_owner($owner_id,$params)
    {
        $this->db->where('owner_id',$owner_id);
        return $this->db->update('owners',$params);
    }
    
    /*
     * function to delete owner
     */
    function delete_owner($owner_id)
    {
        return $this->db->delete('owners',array('owner_id'=>$owner_id));
    }
}
